{
 "title": "Work monitoring",
 "time": { "from": "now-14h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Display power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "power{sensor=\"plug/pracovna\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Table distance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "distance{sensor=\"pracovna/featherTFT\"} * 10",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "hours worked @home in the selected range",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time( (power{sensor=\"plug/pracovna\"} > 30)[$__range:1m] ) / 60"
    }
   ]
  },
  {
   "title": "Average hours per workday @home worked in the last 30 days",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count_over_time( (power{sensor=\"plug/pracovna\"} > 30)[43200m:1m] ) / 60 ) / 20"
    }
   ]
  }
 ]
}